### ISSUE TITLE
Poetry pins minor version of `^0` dependencies

### ISSUE THREAD

**Issue by ravidalon** [rigetti/qcs-api-client-python#3]
Issue Description
-----------------

Using Poetry's `^` syntax for dependencies whose major version is at 0 causes Poetry to pin the minor version of that dependency (see [Poetry's documentation](https://python-poetry.org/docs/dependency-specification/)). This means that the following dependency, for example, pins httpx to version 0.15.5, despite it being release on Oct 2020, and the latest release being 0.22.0

https://github.com/rigetti/qcs-api-client-python/blob/1c1791372f7577240850d1e56fe4c09e10e0f2ef/pyproject.toml#L20

[See also](https://github.com/rigetti/pyquil/issues/1421)

Proposed Solution
-----------------

Unless specifically required for some dependency, change the `^0` dependencies to explicitly allow minor version updates and disallow major version updates:

```toml
httpx = { version=">=0.15.0, <1" }
```

**Comment by dbanty** [comment]
Noted something similar in https://github.com/rigetti/pyquil/issues/1421, but for completeness:

Poetry's behavior is intentional because of the way that [0.x versions in Semantic Versioning](https://semver.org/#spec-item-4) indicate instability. Technically, any version of a 0.x dependency can be a breaking change, but in practice, most projects (including `httpx`) use the minor component to indicate any breaking changes.

There are breaking changes in `httpx >= 0.16.0` which are known to be incompatible with the version of [openapi-python-client](https://github.com/openapi-generators/openapi-python-client) we're using to generate this code. We are tracking a task internally to update the version of the generator we use, but I don't have a timeline on that.

Is there something specific you need in a newer version of `httpx`? Having users who would benefit from the update would help with prioritization.

**Comment by ravidalon** [comment]
> Is there something specific you need in a newer version of `httpx`?

We had a dependency conflict with another package that required a newer version of `httpx`. We managed to solve this conflict in a different manner, so this fix is not required for us anymore.

Thanks for the quick reply (and quick fix in `pyquil`)!

**Comment by dbanty** [comment]
Great! Since you have a workaround for now I'm going to close this issue. Definitely open a new one though if you ever have future dependency issues so we can prioritize updating as needed!
